### ISSUE TITLE
ftpuse + pureftpd not working

### ISSUE THREAD

**Issue by paolomeraviglia** [codeskyblue/boxtool#1]
Hi, testing with win 8.1 / 10 + pureftpd, I can login, browse, read files, delete files, create dirs, but when I try to create a new file or copy an existent file from pc to network drive I receive errors for drive full.

The problem is not present with other ftp software like cyberduck or filezilla

**Comment by codeskyblue** [comment]
我很惊讶这个项目还有人用，因为说明都没有写，我自己都不怎么能看懂了

**Comment by paolomeraviglia** [comment]
Sorry, can you write in english please? As of google translate, you wrote:

I am surprised that this project is also used, because the description did
not write, I can not understand how

I am using in windows 8 and 10 ftpuse. The server side has pureftpd. I can
do everything with ftpuse except upload anything because of "disk full
error", but if I use some other client, including the directory mount of
windows, I can upload without problems. In windows xp it seems to work

Il 05 apr 2017 09:46, "shengxiang" <notifications@github.com> ha scritto:

我很惊讶这个项目还有人用，因为说明都没有写，我自己都不怎么能看懂了

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/codeskyblue/boxtool/issues/1#issuecomment-291781391>,
or mute the thread

**Comment by codeskyblue** [comment]
Sorry, I donot know that you dont understand chinese. This project created 3 years ago and lack of description. Can I ask what are you using for with this project?

**Comment by paolomeraviglia** [comment]
Hi, i'm trying to simply map an ftp directory to a drive in windows. I'm
using from this project only ftpuse.exe. I also tryied the latest version
from the website but it seems to not work properly on win8.1/win10

Thank you!


Il 05 apr 2017 11:59, "shengxiang" <notifications@github.com> ha scritto:

Sorry, I donot know that you dont understand chinese. This project created
3 years ago and lack of description. Can I ask what are you using for with
this project?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/codeskyblue/boxtool/issues/1#issuecomment-291813847>,
or mute the thread

**Comment by codeskyblue** [comment]
^_^ good luck.
